//módulos substituem a anexação de arquivos...
//bons programadores organizam o código em módulos...
//são compartilhados adicionados e removíveis...
//é possível reaproveitar em outras aplicações...
//módulo resolve uma parte específica do código...


//pq usar módulos??
//aplicação da boa prática dry, dont repeat yourself...

//commumJS mto útil

//ES moduls...


